name: My Envio Indexer
contracts:
- name: Base_SpokePool
  handler: src/EventHandlers.ts
  events:
  - event: AdminChanged(address previousAdmin, address newAdmin)
  - event: BeaconUpgraded(address indexed beacon)
  - event: EmergencyDeleteRootBundle(uint256 indexed rootBundleId)
  - event: EnabledDepositRoute(address indexed originToken, uint256 indexed destinationChainId, bool enabled)
  - event: ExecutedRelayerRefundRoot(uint256 amountToReturn, uint256 indexed chainId, uint256[] refundAmounts, uint32 indexed rootBundleId, uint32 indexed leafId, address l2TokenAddress, address[] refundAddresses, address caller)
  - event: FilledV3Relay(address inputToken, address outputToken, uint256 inputAmount, uint256 outputAmount, uint256 repaymentChainId, uint256 indexed originChainId, uint32 indexed depositId, uint32 fillDeadline, uint32 exclusivityDeadline, address exclusiveRelayer, address indexed relayer, address depositor, address recipient, bytes message, (address,bytes,uint256,uint8) relayExecutionInfo)
  - event: Initialized(uint8 version)
  - event: PausedDeposits(bool isPaused)
  - event: PausedFills(bool isPaused)
  - event: RelayedRootBundle(uint32 indexed rootBundleId, bytes32 indexed relayerRefundRoot, bytes32 indexed slowRelayRoot)
  - event: RequestedSpeedUpV3Deposit(uint256 updatedOutputAmount, uint32 indexed depositId, address indexed depositor, address updatedRecipient, bytes updatedMessage, bytes depositorSignature)
  - event: RequestedV3SlowFill(address inputToken, address outputToken, uint256 inputAmount, uint256 outputAmount, uint256 indexed originChainId, uint32 indexed depositId, uint32 fillDeadline, uint32 exclusivityDeadline, address exclusiveRelayer, address depositor, address recipient, bytes message)
  - event: SetHubPool(address indexed newHubPool)
  - event: SetL1Gas(uint32 indexed newL1Gas)
  - event: SetL2TokenBridge(address indexed l2Token, address indexed tokenBridge)
  - event: SetXDomainAdmin(address indexed newAdmin)
  - event: TokensBridged(uint256 amountToReturn, uint256 indexed chainId, uint32 indexed leafId, address indexed l2TokenAddress, address caller)
  - event: Upgraded(address indexed implementation)
  - event: V3FundsDeposited(address inputToken, address outputToken, uint256 inputAmount, uint256 outputAmount, uint256 indexed destinationChainId, uint32 indexed depositId, uint32 quoteTimestamp, uint32 fillDeadline, uint32 exclusivityDeadline, address indexed depositor, address recipient, address exclusiveRelayer, bytes message)
networks:
- id: 1
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0x5c7BCd6E7De5423a257D81B442095A1a6ced35C5
- id: 137
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0x9295ee1d8C5b022Be115A2AD3c30C72E34e7F096
- id: 324
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0xE0B015E54d54fc84a6cB9B666099c46adE9335FF
- id: 8453
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0x09aea4b2242abC8bb4BB78D537A67a245A7bEC64
- id: 42161
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0xe35e9842fceaCA96570B734083f4a58e8F7C5f2A
- id: 59144
  start_block: 0
  end_block: null
  contracts:
  - name: Base_SpokePool
    address:
    - 0x7E63A5f1a8F0B4d0934B2f2327DAED3F6bb2ee75
